//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5pr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ancestor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ancestor()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int Ancestor_code { get; set; }
        public int OrderDishes_code { get; set; }
        public int TableNumber { get; set; }
        public int Staff_code { get; set; }
        public System.DateTime AncestorDate { get; set; }
        public int TaxPrice_code { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual TaxPrice TaxPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
    }
}
