//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5pr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDishes
    {
        public int OrderDishes_code { get; set; }
        public int Order_code { get; set; }
        public int Dishes_code { get; set; }
        public string TotalAmount { get; set; }
        public int Quantity { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Order Order { get; set; }
    }
}
