//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5pr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Services_code { get; set; }
        public int EntertainmentPrograms_code { get; set; }
        public int Menu_code { get; set; }
    
        public virtual EntertainmentPrograms EntertainmentPrograms { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
